config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get '/signup',  to: 'users#new'
  resources :users
  resources :posts, only: %i[create destroy] do
    resources :comments, only: %i[create destroy]
  end

  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  default_scope -> { order(created_at: :desc) }

  validates :user_id, presence: true
  validates :body, presence: true
  validates :body, length: { in: 3..500 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :email, presence: true
  validates :password, presence: true, on: :create, length: { in: 6..72, wrong_lenght: "Password lenght should be in 3-45 characters" }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: %i[facebook]
  mount_uploader :avatar, AvatarUploader
  enum sex: %i[male female]
  enum role: %i[user admin]

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  protect_from_forgery with: :exception

  private 

  def user_not_authorized
    flash[:alert] = "Access denied"
    redirect_to (request.referrer || root_path)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: %i[create destroy]
  before_action :set_comment, only: %i[destroy]
  before_action :pundit_authorize

  def create
    @comment = @post.comments.build(comment_options)
    if @comment.save
      respond_to do |format|
        format.html { redirect_to user_path(@post.user), notice: 'You have added comment' }
        format.js { @new_comment = Comment.new }
      end
    else
      respond_to do |format|
        format.html { render 'users/show' }
        format.js { @new_comment = @comment }
      end
    end
  end
  
  def destroy
    @comment = Comment.find(params[:id])
    if @comment.destroy
      respond_to do |format|
        format.html { redirect_to user_path(@post.user), notice: 'The comment was deleted' }
        format.js
      end
    end
  end
  
  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_options
    comment_params.merge({ user: current_user })
  end

  def comment_params
    params.require(:comment).permit(:body)
  end

  def pundit_authorize
    authorize @comment || Comment
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: :destroy
  before_action :pundit_authorize

  def create
    @post = Post.new(post_options)
    if @post.valid?
      @post.save
      redirect_to user_path(@post.user), notice: 'The post was created'
    else
      @user = current_user
      render 'users/show'
    end
  end

  def destroy
    if @post.destroy
      redirect_to user_path(@post.user), notice: 'The post was deleted'
    else
      redirect_to user_path(@post.user), alert: 'You can not delete this post' 
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_options
    post_params.merge({ user: current_user })
  end

  def post_params
    params.require(:post).permit(:body)
  end

  def pundit_authorize
    authorize @post || Post
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: %i[update edit]
  before_action :pundit_authorize

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    @post = Post.new
    @posts = @user.posts.paginate(page: params[:page])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to user_path
    else
      render 'edit'
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def pundit_authorize
    authorize @user || User
  end

  def user_params
    params.require(:user).permit(:name, :surname, :sex, :date_of_birth, :city, :phone_number, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
  def options_for_sex_select
    User.sexes.keys.map {|sex| [sex.humanize, sex]}
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.haml
%div.comment{ data: { id: "#{comment.id}" } }
  = link_to comment.post.user.name, user_path(comment.post.user)
  %span.date
    commented
    = time_ago_in_words(comment.created_at)
    ago
  %p
    = comment.body
  - if policy(comment).destroy?
    = link_to 'Delete comment', post_comment_path(comment.post, comment), method: :delete, remote: true, confirm: 'Are you sure?'
  %hr

app/views/comments/_comment_form.html.haml
= simple_form_for(comment, url: url, remote: true) do |f|
  = render 'shared/error_messages', object: f.object
  = f.text_area :body, placeholder: "Write a comment..."
  = f.submit 'Post comment'

app/views/comments/create.js.erb
$('.post[data-post-id="' + <%= @post.id %> + '"] .comment_form').html("<%= escape_javascript(render partial: 'comments/comment_form', locals: { comment: @new_comment, url: post_comments_path(@post) }) %>");
<% if @comment.id.present? %>
  $("<%= escape_javascript(render @comment) %>").prependTo('.post[data-post-id="' + <%= @post.id %> + '"] .comments');
<% end %>

app/views/comments/destroy.js.erb
$('.comment[data-id="' + <%= @comment.id %> + '"]').fadeOut();

app/views/common/_navbar.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle.collapsed(data-target="#navbar-top" data-toggle="collapse" type="button")
        %span.sr-only Toggle navigation
      = link_to "Home", root_url, class: "navbar-brand"
    #navbar-top.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li= link_to 'Sign out', destroy_user_session_path, method: :delete
          %li= link_to "Users", users_path
          %li= link_to current_user.email, current_user
        - else
          %li= link_to 'Sign up', new_user_registration_path
          %li= link_to 'Sign in', user_session_path
          %li= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path

app/views/home/index.html.haml
%h1 Home#index
%p Find me in app/views/home/front.html.haml

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta(content="text/html; charset=UTF-8" http-equiv="Content-Type")/
    %title Social Network
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = render 'common/navbar'
    - if notice
      %p.alert.alert-success= notice
    - if alert
      %p.alert.alert-danger= alert
    .container-fluid
      .row
        .col-md-2
        .col-md-8
          = yield
        .col-md-2

app/views/posts/_post.html.haml
.post{ data: { post_id: "#{post.id}" } }
  %li(id="post-#{post.id}")
    %span.user
      = link_to post.user.name, post.user
    %span.body
      = post.body
    %span.timestamp
      posted
      = time_ago_in_words(post.created_at)
      ago
      - if policy(post).destroy?
        = link_to 'Delete post', post_path(post), method: :delete, confirm: 'Are you sure?'
    %hr
    %p
      = link_to "Comments", "#", class: "comments-link", data: { post_id: "#{post.id}" }

  %section.comments-section
    %ol
      %div.comment_form
        = render partial: 'comments/comment_form', locals: { comment: Comment.new, url: post_comments_path(post) }
      %div.comments
        = render partial: 'comments/comment', collection: post.comments.reverse

app/views/posts/_post_form.html.haml
= simple_form_for(post) do |f|
  = render 'shared/error_messages', object: f.object
  .fieldset
    = f.text_area :body, placeholder: "Write new post..."
  = f.submit "Post", class: "btn btn-primary"

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  #error_explanation
    .alert.alert-danger
      The form contains #{pluralize(object.errors.count, "error")}.
    %ul
      - object.errors.full_messages.each do |msg|
        %li= msg

app/views/users/edit.html.haml
- provide(:title, "Edit user")
%h1 Update your profile
.row
  .col-md-6.col-md-offset-3
    = simple_form_for(@user, html: { multipart: true} ) do |f|
      = render partial: '/shared/error_messages', locals: {object: f.object} 
      = f.label :name
      = f.text_field :name, class: 'form-control'
      = f.label :surname
      = f.text_field :surname, class: 'form-control'
      = f.input :sex, as: :select, collection: options_for_sex_select, input_html: { class: "form-control" }
      = f.input :date_of_birth, as: :date, html5: true
      = f.label :city
      = f.text_field :city, class: 'form-control'
      = f.label :phone_number
      = f.text_field :phone_number, class: 'form-control'
      = f.file_field :avatar
      = f.submit "Save changes", class: "btn btn-primary"

app/views/users/index.html.haml
- provide(:title, 'All users')
%h1 All users
%ul.users
  - @users.each do |user|
    %li
      = link_to user.name, user

app/views/users/show.html.haml
.row
  %aside.col-md-4
    %section
      %h1.col-md-1
        = @user.name
        = @user.surname
        = image_tag @user.avatar.url(:thumb) if @user.avatar?
    %address  
      %strong User's information:
      %br
      = @user.sex
      %br/
      = @user.email
      %br/
      = @user.phone_number
      %br/
      = @user.date_of_birth
      %br/
      = @user.city
      - if policy(@user).edit?
        = link_to "Edit", edit_user_path(@user)
  .col-md-6
    %h3
      Posts (#{@user.posts.count})
    - if current_user.id == @user.id
      = render partial: 'posts/post_form', locals: { post: @post }
    %ol.posts
      = render @user.posts